import { Localization } from "./localization.type";

export const ru: Localization = {
  aboutUs: "О нас",
  beTheFirstToFindOutAboutNewProducts: "Узнайте  первым о новинках",
  catalog: "Каталог",
  categories: "Категории",
  color: "Цвет",
  company: "Компания",
  contacts: "Контакты",
  favourites: "Избранное",
  jackets: "Куртки",
  coats: "Пальто",
  furCoats: "Шубы",
  parkas: "Парки",
  seeNewProducts: "Смотреть новинки",
  size: "Размер",
  sortBy: "Сортировка по",
  subscribe: "Подписаться",
  subscribeAgreement:
    "Нажимая на кнопку «Подписаться», я соглашаюсь на обработку моих персональных данных и ознакомлен(а) с условиями конфиденциальности.",
  publicOffer: "Публичная офферта",
  price: "Цена",
  paymentAndDelievery: "Оплата и доставка",
  new: "Новинки",
  newCollection: "Новая коллекция",
  termsOfReturn: "Условия возврата",
  toTheBuyer: "Покупателю",
  yourEmail: "Ваш email",
  useful: "Полезное",
  bonusProgram: "Бонусная программа",
  privacyPolicy: "Политика конфиденциальности",
};
